apiVersion: v1
kind: Service
metadata:
  name: hawkthorne
  labels:
    app: hawkthorne
spec:
  ports:
  - port: 80
    targetPort: 9000
    name: http
  selector:
    app: hawkthorne
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hawkthorne
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hawkthorne
    spec:
      containers:
      - name: app
        image: hawkthorne/hawkthorne:latest
        ports:
        - containerPort: 9000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hawkthorne-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: hawkthorne.com
    http:
      paths:
      - backend:
          serviceName: hawkthorne
          servicePort: 13000
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: hawkthorne
  name: hawkthorne-config
data:
  application.conf: |
    foo = "bar"
---
